### ISSUE TITLE
Support non-public cloud types for the Metric Receiver

### ISSUE THREAD

**Issue by nikitawasthi20** [logzio/azure-monitor-metrics-receiver#4]
Currently when we are creating the Azure clients using NewClientSecretCredential, we pass nil in the options field. However, if we take the cloud type as a parameter and accordingly set the cloud configuration using the enum defined in "github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud", we can also support non-public cloud types.

**Comment by ZPascal** [comment]
I think, the issue should be solved by following [PR](#17).

**Comment by ZPascal** [comment]
@8naama I think, you can also close this issue.

**Comment by 8naama** [comment]
Thank you @ZPascal!

Hey, @nikitawasthi20, let us know if the new version (`v1.1.0`) worked well for your use case 🙏🏼
